version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  
  redis:
    image: 'redis'
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
    links:
      - db
      - elasticsearch
      - redis
    environment:
      # - ELASTIC_HOST="elasticsearch"
      # - ELASTIC_PORT="9200"
      - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  redis:
  elasticsearch: 